//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 02:48:29 PM IST 
//


package embryo.in.demo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the embryo.in.demo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Employees_QNAME = new QName("http://in.embryo/demo", "employees");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: embryo.in.demo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmployeesType }
     * 
     */
    public EmployeesType createEmployeesType() {
        return new EmployeesType();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public EmployeeType createEmployeeType() {
        return new EmployeeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmployeesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://in.embryo/demo", name = "employees")
    public JAXBElement<EmployeesType> createEmployees(EmployeesType value) {
        return new JAXBElement<EmployeesType>(_Employees_QNAME, EmployeesType.class, null, value);
    }

}
